#!/usr/bin/env python3

# ovpncheck
# Copyright (C) 2026  Salar Nosrati-Ershad <salar@roverc.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
import argparse

SUPPORTED = {
    "client",
    "dev",
    "remote",
    "remote-cert-tls",
    "cipher",
    "auth",
    "nobind",
    "verb",
    "key-direction",
    "push-peer-info",
    "proto",
    "setenv",
    "reneg-sec",
    "sndbuf",
    "rcvbuf",
    "auth-user-pass",
    "ns-cert-type",
    "keepalive",
    "float",
    "mute-replay-warnings",
    "tls-version-min",
    "comp-lzo",
    "remote-random-hostname",
    "dhcp-option",
    "client-cert-not-required",
    "static-challenge",
    "dev-type",
    "tls-client",
    "compress",
    "http-proxy",
    "server-poll-timeout",
    "tun-mtu",
    "ca",
    "cert",
    "key",
    "tls-auth",
    "fast-io",
    "ignore-unknown-option",
    "redirect-gateway",
    "verify-x509-name",
    "inactive",
}

IGNORED = {
    "down",
    "down-pre",
    "ifconfig-noexec",
    "ipchange",
    "learn-address",
    "plugin",
    "route-noexec",
    "route-pre-down",
    "route-up",
    "setenv-safe",
    "tls-export-cert",
    "tls-verify",
    "up",
    "up-delay",
    "x509-track",
    "allow-pull-fqdn",
    "bind",
    "local",
    "lport",
    "mlock",
    "mtu-disc",
    "mtu-test",
    "persist-local-ip",
    "persist-remote-ip",
    "shaper",
    "tls-exit",
    "allow-compression",
    "allow-recursive-routing",
    "auth-nocache",
    "auth-retry",
    "compat-mode",
    "connect-retry",
    "connect-retry-max",
    "connect-timeout",
    "data-ciphers",
    "data-ciphers-fallback",
    "disable-dco",
    "disable-occ",
    "engine",
    "explicit-exit-notify",
    "group",
    "ifconfig-nowarn",
    "ip-win32",
    "link-mtu",
    "machine-readable-output",
    "mark",
    "mute",
    "ncp-ciphers",
    "nice",
    "opt-verify",
    "passtos",
    "persist-key",
    "persist-tun",
    "preresolve",
    "providers",
    "remap-usr1",
    "reneg-bytes",
    "reneg-pkts",
    "replay-window",
    "resolv-retry",
    "route-method",
    "show-net-up",
    "socket-flags",
    "supress-timestamps",
    "tcp-nodelay",
    "tls-version-max",
    "udp-mtu",
    "user",
}

UNSUPPORTED = {
    "mtu-dynamic",
    "no-replay",
    "no-name-remapping",
    "compat-names",
    "ncp-disable",
    "genkey",
    "mktun",
    "rmtun",
    "show-ciphers",
    "show-curves",
    "show-digests",
    "show-engines",
    "show-groups",
    "show-tls",
    "test-crypto",
    "protocol-flags",
    "peer-id",
    "key-derivation",
    "ping-exit",
    "parameter",
    "echo",
    "auth-token-user",
    "auth-token",
    "management",
    "askpass",
    "capath",
    "cd",
    "chroot",
    "client-nat",
    "cryptoapicert",
    "daemon",
    "errors-to-stderr",
    "gremlin",
    "lladdr",
    "log",
    "log-append",
    "memstats",
    "msg-channel",
    "ping-timer-rem",
    "single-session",
    "socks-proxy",
    "status",
    "status-version",
    "syslog",
    "tls-server",
    "tun-mtu-extra",
    "verify-hash",
    "win-sys",
    "writepid",
    "x509-username-field",
    "auth-gen-token",
    "auth-gen-token-secret",
    "auth-user-pass-verify",
    "bcast-buffers",
    "block-outside-dns",
    "ccd-exclusive",
    "client-config-dir",
    "client-connect",
    "client-disconnect",
    "client-to-client",
    "connect-freq",
    "dh",
    "disable",
    "duplicate-cn",
    "hash-size",
    "ifconfig-ipv6-pool",
    "ifconfig-pool",
    "ifconfig-pool-persist",
    "ifconfig-push",
    "ifconfig-push-constraint",
    "iroute",
    "iroute-ipv6",
    "max-clients",
    "max-routes-per-client",
    "push",
    "push-remove",
    "push-reset",
    "server",
    "server-bridge",
    "server-ipv6",
    "state-routes-check",
    "tls-crypt-v2-verify",
    "username-as-common-name",
    "verify-client-cert",
    "vlan-accept",
    "vlan-pvid",
    "vlan-tagging",
}


def main():
    parser = argparse.ArgumentParser(prog="ovpncheck")
    parser.add_argument("file", type=argparse.FileType())
    args = parser.parse_args()
    with args.file as f:
        for ln, line in enumerate(iter(f.readline, ""), 1):
            keyword = line.split()[0].strip()
            if keyword:
                if keyword in IGNORED:
                    print(f'{ln}: "{keyword}" is ignored')
                if keyword in UNSUPPORTED:
                    print(f'{ln}: "{keyword}" is ignored')


if __name__ == "__main__":
    main()
